openapi: 3.1.0
info:
  title: API для проекта «FIT FRIENDS»
  description: FitFriends — это онлайн площадка для поиска тренировок и их создания. Веб-приложение (сайт) функционирует как смесь соцсети и биржи объявлений. Тренеры создают тренировки, а пользователи могут покупать их и заниматься по ним, приглашать других пользователей на совместные тренировки, а тренеров просить провести индивидуальную тренировку.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

tags:
  - name:
    description: Действия с

paths:

components:
  schemas:
