# Уведомления(общее)
## Список уведомлений

GET http://localhost:4000/notifications/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1Mzc4MDcxOWI3YTcyYjZlZjFhYmM1MiIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2OTg3Njk1NjEsImV4cCI6MTY5ODc3MDQ2MX0._9cWkl61L90bFug2YhutEqKs1yDQW0O9UAWMKru07o8

###

## Удалить уведомление

DELETE http://localhost:4000/notifications/653fd849cab8666a57015433 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1Mzc4MDcxOWI3YTcyYjZlZjFhYmM1MiIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2OTg3Njk1NjEsImV4cCI6MTY5ODc3MDQ2MX0._9cWkl61L90bFug2YhutEqKs1yDQW0O9UAWMKru07o8

###
