# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Sasha",
  "email": "feliugin51ek52@mail.net",
  "password": "123456",
  "gender": "мужской",
  "location": "звёздная",
  "backgroundImage": "image.png",
  "trainingLevel": "любитель",
  "workoutTypes": ["стрейчинг", "аэробика"],
  "workoutDuration": "10-30 мин",
  "caloriesToBurn": 1000,
  "caloriesToSpend": 1002,
  "readinessForWorkout": true
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "Trainer8046@example.com",
  "password": "123456"
}

###

## Завершение сеанса

POST http://localhost:4000/users/logout HTTP/1.1
Content-Type: application/json

###


## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVzZXI1NDU2QGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1NDM2ZWEwNjczMjJhYzYwNzQxZWZjYyIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2OTg5MjM5MTMsImV4cCI6MTY5ODkyNDgxM30.GvcpA8fTt2E1g9nFzR1_5hZbXA3RPgZGN3Y25j5MsIc

###

## Обновление токена

GET http://localhost:4000/users/refresh HTTP/1.1
Content-Type: application/json

{
  "email": "feliugin@mail.net",
  "password": "123456"
}
###

## Обновление пользователя по id

PUT http://localhost:4000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVzZXI1NDU2QGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1NDM2ZWEwNjczMjJhYzYwNzQxZWZjYyIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2OTg5MjU2OTgsImV4cCI6MTY5ODkyNjU5OH0.yF8z7sw79g4uPtFmiPDAS070BUwvOCmFWP6Y_bSk41M

{
  "name": "",
  "role": "тренер"
}
###

## Список пользователей

GET http://localhost:4000/users?sortBy=тренер&workoutTypes=аэробика,бокс&page=3&limit=3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1MzdlNjU5YzM1YWJlZDc0ODgwYTEwMSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2OTg0MDA4MzMsImV4cCI6MTY5OTY5NjgzM30.gTWNG7qbIDSZ6rw7-MKBzfQfGwfZ-22vdqfTMIGjeW8

###

## Пользователь по идентификатору

GET http://localhost:4000/users/65436ea167322ac60741efe5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVzZXI1NDU2QGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1NDM2ZWEwNjczMjJhYzYwNzQxZWZjYyIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2OTg5MjkzMjMsImV4cCI6MTY5ODkzMDIyM30.EEn38K2hsTdJRtVc0WKTVFkfroSYXJVEah2ICkd2h2Q
###

