# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Sasha",
  "email": "feliugin1@mail.net",
  "password": "123456",
  "gender": "мужской",
  "location": "Звёздная",
  "backgroundImage": "image.png",
  "trainingLevel": "профессионал",
  "workoutTypes": "бокс",
  "workoutDuration": "10-30 мин",
  "caloriesToBurn": 1000,
  "caloriesToSpend": 1002,
  "readinessForWorkout": true,
  "traningCount": 1
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user5@example.com",
  "password": "123456"
}

###

## Поиск пользователя по email

GET http://localhost:4000/users/email HTTP/1.1
Content-Type: application/json

{
  "email": "user5@example.com"
}
###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXI1QGV4YW1wbGUuY29tIiwiaWQiOiI2NTI2YzExODU2ZmRlOTJiNmViMDNmNGMiLCJpYXQiOjE2OTcxMjQ4MDksImV4cCI6MTY5NzEyNTcwOX0.8RXzz5gPP6lpD3H10AVqOxbJ0kwPkHP6lJs2qUK_3SY

###

## Обновление пользователя по id

PUT http://localhost:4000/users/6526c11856fde92b6eb03f4c HTTP/1.1
Content-Type: application/json

{
  "email": "user5@example.com",
  "name": "Userr"
}
###
