# Тренировки(кабинет тренера)

## Создать новую тренировку

POST http://localhost:4000/trainings/trainer-room/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlRyYWluZXI4MDQ2QGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1NDM2ZWExNjczMjJhYzYwNzQxZWZlNSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJpYXQiOjE2OTkzNTU2MDQsImV4cCI6MTY5OTM1NjUwNH0.dSh7duQJ2etkd3fuBSB-zPEQYI-yOMf4DmybsUqXR8k

{
  "name": "Test",
  "backgroundImage": "image.png",
  "trainingLevel": "любитель",
  "workoutType": "бокс",
  "workoutDuration": "80-100 мин",
  "price": 999,
  "calories": 1000,
  "description": "отжиматься, отжиматься и еще раз отжиматьсяБ по другому никак",
  "genderPreference": "для мужчин",
  "video": "video.mov",
  "specialOffer": true
}

###

## Тренировка по идентификатору

GET http://localhost:4000/trainings/653780719b7a72b6ef1abc60 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyYWluZXJAbWFpbC5uZXQiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlkIjoiNjUzYWI1MTRhNGRiMDJlNzEyNTRlMTZhIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImlhdCI6MTY5ODM5MDg0NiwiZXhwIjoxNjk5Njg2ODQ2fQ.boKU52TZBDbo_CnVkQ55_rHJEE6LyuZdr54nVy4R5VE
###

## Обновление существующей тренировки

PUT http://localhost:4000/trainings/trainer-room/653780719b7a72b6ef1abc60 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyYWluZXIxQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1Mzc4MDcxOWI3YTcyYjZlZjFhYmM1NyIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJpYXQiOjE2OTg3NTQ2MjMsImV4cCI6MTY5ODc1NTUyM30.jj1saRGJ8yfsjGSwf1BEaNWAsKIPdO4OwGY0ckEAIkk

{
  "specialOffer": false
}

###

## Список тренировок
GET http://localhost:4000/trainings/trainer-room/653b987ece78ce7270b47d0f?page=2&limit=26 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyYWluZXIxMTFAbWFpbC5uZXQiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlkIjoiNjUzYjk4N2VjZTc4Y2U3MjcwYjQ3ZDBmIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImlhdCI6MTY5ODc3MjEzNywiZXhwIjoxNjk4NzczMDM3fQ.R4P11L_MPrWDnJqIfBZVxJj_v9E9B1PX04FkTjCWIsc

###

# Тренировки
## Список тренировок
GET http://localhost:4000/trainings?workoutTypes=бег HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5ydSIsImlkIjoiNjU3ODRiM2E5YzQ1YjhkMzg0NzYyYWE5Iiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTcwMjM4ODk1NiwiZXhwIjoxNzAyMzg5ODU2fQ.970sOBNWlIoshxss-lTMCvSpn81qisY1Zur18yvlRpY

###


## Отправка видео для тренировки

POST http://localhost:4000/trainings/658d35d4d61eb0322c6f0f29/video HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="sample_640x360.mov"
Content-Type: video/quicktime

< C:\Users\Test\Downloads\sample_640x360.mov
------WebKitFormBoundary7MA4YWxkTrZu0gW--
