export const TRAINING_NAME_CONSTRAINTS = {
  MIN_LENGTH: 1,
  MAX_LENGTH: 15,
};

export const CALORIES_CONSTRAINTS = {
  MIN: 1000,
  MAX: 5000,
};

export const DESCRIPTION_CONSTRAINTS = {
  MIN_LENGTH: 10,
  MAX_LENGTH: 140,
};
