# Друзья

## Список друзей
GET http://localhost:4000/friends?limit=3&page=1&sortDirection=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5ydSIsImlkIjoiNjU3ODRiM2E5YzQ1YjhkMzg0NzYyYWE5Iiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTcwMjYzODY3NCwiZXhwIjoxNzAyNjM5NTc0fQ.-Beml_eZNR2WdEIEb5HbCkFL-zJHGOt8U3E7x8h7AsY

###

## Добавить друга

POST http://localhost:4000/friends/657b4ab88ab83d438ebb154e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5ydSIsImlkIjoiNjU3ODRiM2E5YzQ1YjhkMzg0NzYyYWE5Iiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTcwMjYzODY3NCwiZXhwIjoxNzAyNjM5NTc0fQ.-Beml_eZNR2WdEIEb5HbCkFL-zJHGOt8U3E7x8h7AsY

###

## Удалить друга

DELETE http://localhost:4000/friends/657b4ab88ab83d438ebb154e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5ydSIsImlkIjoiNjU3ODRiM2E5YzQ1YjhkMzg0NzYyYWE5Iiwicm9sZSI6ItC_0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsImlhdCI6MTcwMjYzODY3NCwiZXhwIjoxNzAyNjM5NTc0fQ.-Beml_eZNR2WdEIEb5HbCkFL-zJHGOt8U3E7x8h7AsY
###
