# Друзья

## Список друзей
GET http://localhost:4000/friends?limit=3&page=1&sortDirection=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVzZXI1NTVAZXhhbXBsZS5jb20iLCJpZCI6IjY1NmUwY2Y2Njg1YmEwNjJiMmU3NjU0YSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE3MDE4ODE5MjIsImV4cCI6MTcwMTg4MjgyMn0.1ozp12L96yL2Ij4wHBV-k2eu6j9UFHqjMQI5aGzLN-s

###

## Добавить друга

POST http://localhost:4000/friends/65436ea167322ac60741efe0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVzZXI1NTVAZXhhbXBsZS5jb20iLCJpZCI6IjY1NmUwY2Y2Njg1YmEwNjJiMmU3NjU0YSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE3MDE4ODE5MjIsImV4cCI6MTcwMTg4MjgyMn0.1ozp12L96yL2Ij4wHBV-k2eu6j9UFHqjMQI5aGzLN-s

###

## Удалить друга

DELETE http://localhost:4000/friends/65436ea167322ac60741efe0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlVzZXI1NTVAZXhhbXBsZS5jb20iLCJpZCI6IjY1NmUwY2Y2Njg1YmEwNjJiMmU3NjU0YSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE3MDE4ODE5MjIsImV4cCI6MTcwMTg4MjgyMn0.1ozp12L96yL2Ij4wHBV-k2eu6j9UFHqjMQI5aGzLN-s

###
