# Персональные тренировки/совместные тренировки()

## Создать запрос на тренировку

POST http://localhost:4000/requests/user/653780719b7a72b6ef1abc52 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpZCI6IjY1Mzc4MDcxOWI3YTcyYjZlZjFhYmM1MiIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJpYXQiOjE2OTg3NzE2MTQsImV4cCI6MTY5ODc3MjUxNH0.GoT-oT1H2g5LDWNevg0rJQVxKcNHIJGqv5laun8_i7M

{
  "requestType": "personal"
}

###

## изменить статус заявки

PATCH http://localhost:4000/requests/653fcfe8e6981500b541682d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyYWluZXIxMTFAbWFpbC5uZXQiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlkIjoiNjUzYjk4N2VjZTc4Y2U3MjcwYjQ3ZDBmIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImlhdCI6MTY5ODY4NTc2MSwiZXhwIjoxNjk5OTgxNzYxfQ.3ZFebWrzGMsyAOlQIVEZLBt7FG-vUR6ku56eYk4wrqQ

{
  "status": "отклонён"
}

###
